"""
Fetch CreelCat survey weather using IEM ASOS/AWOS airport data.

For each unique (lat_r, lon_r, year, month) combination in the CreelCat
survey data, fetches monthly weather from IEM (Iowa Environmental Mesonet)
ASOS/AWOS stations. IEM has NO rate limits and excellent pressure coverage.

For the ~3,258 records missing from Open-Meteo, this provides:
  - Monthly pressure (mean + range) - critical for bass behavior
  - Temperature (mean, max, min, range)
  - Precipitation (total, rain days)
  - Wind (max, mean)
  - Humidity

Usage:
    python scripts/fetch_creel_weather_noaa.py [--resume] [--test N]

Output:
    castline/validation/data/raw/creelcat_weather_noaa.csv

IEM has no rate limits but we use 0.1s delays to be respectful.
"""

from __future__ import annotations

import argparse
import calendar
import math
import sys
import time
from io import StringIO
from pathlib import Path

import numpy as np
import pandas as pd
import requests

# Project root
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

SURVEY_PATH = ROOT / "castline" / "validation" / "data" / "raw" / "creel" / "Survey_Data.csv"
CREEL_CPUE = ROOT / "castline" / "validation" / "data" / "raw" / "creel_cpue_bass.csv"
OUT_PATH = ROOT / "castline" / "validation" / "data" / "raw" / "creelcat_weather_noaa.csv"
STATION_CACHE = ROOT / "castline" / "validation" / "data" / "raw" / "iem_asos_stations.csv"

ASOS_URL = "https://mesonet.agron.iastate.edu/cgi-bin/request/asos.py"


def haversine_km(lat1, lon1, lat2, lon2):
    R = 6371.0
    phi1, phi2 = math.radians(lat1), math.radians(lat2)
    dphi = math.radians(lat2 - lat1)
    dlam = math.radians(lon2 - lon1)
    a = math.sin(dphi / 2) ** 2 + math.cos(phi1) * math.cos(phi2) * math.sin(dlam / 2) ** 2
    return R * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))


def load_stations():
    """Load ASOS station list (generated by iem_pressure_lookup.py)."""
    if STATION_CACHE.exists():
        df = pd.read_csv(STATION_CACHE)
        print(f"  Loaded {len(df)} ASOS/AWOS stations from cache")
        return df
    # If not cached, generate it
    from iem_pressure_lookup import fetch_all_asos_stations
    return fetch_all_asos_stations()


def find_nearest_station(lat, lon, stations_df):
    """Find nearest ASOS station."""
    dists = stations_df.apply(
        lambda r: haversine_km(lat, lon, r["lat"], r["lon"]), axis=1
    )
    idx = dists.idxmin()
    return stations_df.loc[idx]["station_id"], dists[idx]


def fetch_iem_monthly(station_id, year, month):
    """
    Fetch all ASOS observations for a station in a given month.
    Returns monthly aggregated weather stats dict, or None.
    """
    last_day = calendar.monthrange(year, month)[1]

    params = {
        "station": station_id,
        "data": ["mslp", "alti", "tmpf", "dwpf", "drct", "sknt", "p01i", "relh"],
        "year1": year, "month1": month, "day1": 1,
        "year2": year, "month2": month, "day2": last_day,
        "tz": "UTC",
        "format": "comma",
        "missing": "M",
        "trace": "T",
        "direct": "no",
        "report_type": ["3", "4"],
    }

    try:
        resp = requests.get(ASOS_URL, params=params, timeout=60)
        if resp.status_code != 200:
            return None

        lines = [l for l in resp.text.split("\n") if not l.startswith("#")]
        text = "\n".join(lines)
        if len(text.strip()) < 20:
            return None

        df = pd.read_csv(StringIO(text))
        df = df.replace("M", np.nan)
        df = df.replace("T", 0.001)

        for col in ["mslp", "alti", "tmpf", "dwpf", "drct", "sknt", "p01i", "relh"]:
            if col in df.columns:
                df[col] = pd.to_numeric(df[col], errors="coerce")

        if "valid" in df.columns:
            df["valid"] = pd.to_datetime(df["valid"], errors="coerce")
            df["date"] = df["valid"].dt.date

        if len(df) == 0:
            return None

        result = {}

        # Temperature (F -> C)
        if "tmpf" in df.columns:
            valid_t = df["tmpf"].dropna()
            if len(valid_t) > 0:
                temps_c = (valid_t - 32) * 5.0 / 9.0
                result["wx_temp_mean"] = round(float(temps_c.mean()), 2)
                result["wx_temp_max"] = round(float(temps_c.max()), 2)
                result["wx_temp_min"] = round(float(temps_c.min()), 2)
                result["wx_temp_range"] = round(float(temps_c.max() - temps_c.min()), 2)

        # Pressure (mslp is in mb = hPa)
        if "mslp" in df.columns:
            valid_p = df["mslp"].dropna()
            if len(valid_p) > 0:
                result["wx_pressure_mean"] = round(float(valid_p.mean()), 1)
                result["wx_pressure_range"] = round(float(valid_p.max() - valid_p.min()), 1)

        # Fallback: altimeter setting -> hPa
        if "wx_pressure_mean" not in result and "alti" in df.columns:
            valid_a = df["alti"].dropna()
            if len(valid_a) > 0:
                p_hpa = valid_a * 33.8639
                result["wx_pressure_mean"] = round(float(p_hpa.mean()), 1)
                result["wx_pressure_range"] = round(float(p_hpa.max() - p_hpa.min()), 1)

        # Wind (knots -> kph)
        if "sknt" in df.columns:
            valid_w = df["sknt"].dropna()
            if len(valid_w) > 0:
                wind_kph = valid_w * 1.852
                result["wx_wind_max"] = round(float(wind_kph.max()), 1)
                result["wx_wind_mean"] = round(float(wind_kph.mean()), 1)

        # Precipitation (inches -> mm, sum by day then total)
        if "p01i" in df.columns and "date" in df.columns:
            daily_precip = df.groupby("date")["p01i"].sum() * 25.4
            result["wx_precip_total"] = round(float(daily_precip.sum()), 1)
            result["wx_precip_days"] = int((daily_precip > 0.254).sum())

        # Humidity
        if "relh" in df.columns:
            valid_h = df["relh"].dropna()
            if len(valid_h) > 0:
                result["wx_humidity_mean"] = round(float(valid_h.mean()), 0)

        # Days with data
        if "date" in df.columns:
            result["n_days_data"] = df["date"].nunique()

        return result if result else None

    except Exception as e:
        print(f"    Error fetching IEM for {station_id} {year}-{month}: {e}")
        return None


def build_unique_keys_from_survey(survey: pd.DataFrame) -> pd.DataFrame:
    """Build unique (lat_r, lon_r, year, month) weather keys from Survey_Data."""
    survey = survey[survey["Lat"].notna() & survey["Lon"].notna()].copy()

    dates = pd.to_datetime(survey["Start_Date"], errors="coerce")
    month_names = {
        "January": 1, "February": 2, "March": 3, "April": 4,
        "May": 5, "June": 6, "July": 7, "August": 8,
        "September": 9, "October": 10, "November": 11, "December": 12,
    }
    survey["month_num"] = dates.dt.month
    mask = survey["month_num"].isna()
    if mask.any():
        survey.loc[mask, "month_num"] = survey.loc[mask, "Start_Month"].map(month_names)
    survey["month_num"] = survey["month_num"].fillna(6).astype(int)

    survey["lat_r"] = survey["Lat"].round(0)
    survey["lon_r"] = survey["Lon"].round(0)
    survey["year"] = survey["Year"].astype(int)

    keys = (
        survey[["lat_r", "lon_r", "year", "month_num"]]
        .drop_duplicates()
        .rename(columns={"month_num": "month"})
        .reset_index(drop=True)
    )
    keys = keys[(keys["year"] >= 1940) & (keys["year"] <= 2024)].reset_index(drop=True)
    keys["weather_key"] = (
        keys["lat_r"].astype(int).astype(str) + "_" +
        keys["lon_r"].astype(int).astype(str) + "_" +
        keys["year"].astype(str) + "_" +
        keys["month"].astype(str)
    )
    return keys


def build_unique_keys_from_cpue(cpue: pd.DataFrame) -> pd.DataFrame:
    """Build unique (lat_r, lon_r, year, month) weather keys from creel_cpue_bass."""
    cpue["date_dt"] = pd.to_datetime(cpue["date"], errors="coerce")
    cpue["year"] = cpue["date_dt"].dt.year
    cpue["month"] = cpue["date_dt"].dt.month
    cpue["lat_r"] = cpue["latitude"].round(0)
    cpue["lon_r"] = cpue["longitude"].round(0)

    keys = (
        cpue[["lat_r", "lon_r", "year", "month"]]
        .dropna()
        .drop_duplicates()
        .reset_index(drop=True)
    )
    keys["lat_r"] = keys["lat_r"].astype(int)
    keys["lon_r"] = keys["lon_r"].astype(int)
    keys["year"] = keys["year"].astype(int)
    keys["month"] = keys["month"].astype(int)
    keys["weather_key"] = (
        keys["lat_r"].astype(str) + "_" +
        keys["lon_r"].astype(str) + "_" +
        keys["year"].astype(str) + "_" +
        keys["month"].astype(str)
    )
    return keys


def _empty_record(lat_r, lon_r, year, month, wkey):
    return {
        "weather_key": wkey,
        "lat_r": lat_r,
        "lon_r": lon_r,
        "year": year,
        "month": month,
        "wx_temp_mean": float("nan"),
        "wx_temp_max": float("nan"),
        "wx_temp_min": float("nan"),
        "wx_temp_range": float("nan"),
        "wx_precip_total": float("nan"),
        "wx_precip_days": 0,
        "wx_wind_max": float("nan"),
        "wx_wind_mean": float("nan"),
        "wx_pressure_mean": float("nan"),
        "wx_pressure_range": float("nan"),
        "wx_humidity_mean": float("nan"),
        "station_id": None,
        "station_distance_km": float("nan"),
        "n_days_data": 0,
    }


def _save_checkpoint(records, path):
    pd.DataFrame(records).to_csv(path, index=False)


OUT_COLS = [
    "weather_key", "lat_r", "lon_r", "year", "month",
    "wx_temp_mean", "wx_temp_max", "wx_temp_min", "wx_temp_range",
    "wx_precip_total", "wx_precip_days",
    "wx_wind_max", "wx_wind_mean",
    "wx_pressure_mean", "wx_pressure_range",
    "wx_humidity_mean",
    "station_id", "station_distance_km", "n_days_data",
]


def main():
    parser = argparse.ArgumentParser(
        description="Fetch CreelCat weather via IEM ASOS/AWOS"
    )
    parser.add_argument("--resume", action="store_true",
                        help="Resume from checkpoint/existing output file")
    parser.add_argument("--test", type=int, default=0,
                        help="Only fetch N keys for testing")
    parser.add_argument("--source", choices=["survey", "cpue"], default="cpue",
                        help="Data source: Survey_Data.csv or creel_cpue_bass.csv")
    args = parser.parse_args()

    print("=" * 60)
    print("CreelCat Weather Fetch -- IEM ASOS/AWOS")
    print("=" * 60)

    # Build unique keys
    if args.source == "survey" and SURVEY_PATH.exists():
        survey = pd.read_csv(SURVEY_PATH, low_memory=False)
        print(f"Loaded {len(survey)} surveys from {SURVEY_PATH}")
        keys = build_unique_keys_from_survey(survey)
    elif CREEL_CPUE.exists():
        cpue = pd.read_csv(CREEL_CPUE)
        print(f"Loaded {len(cpue)} records from {CREEL_CPUE}")
        keys = build_unique_keys_from_cpue(cpue)
    else:
        print(f"ERROR: No input data found at {CREEL_CPUE} or {SURVEY_PATH}")
        sys.exit(1)

    print(f"Unique weather keys: {len(keys)}")

    if args.test > 0:
        keys = keys.head(args.test)
        print(f"  (TEST MODE: limiting to {len(keys)} keys)")

    # Load stations
    stations = load_stations()

    # Resume support
    existing_keys = set()
    results = []
    if args.resume and OUT_PATH.exists():
        existing_df = pd.read_csv(OUT_PATH)
        existing_keys = set(existing_df["weather_key"].values)
        results = existing_df.to_dict("records")
        print(f"  Resuming: {len(existing_keys)} already fetched")

    # Station cache by rounded lat/lon
    station_cache = {}

    to_fetch = keys[~keys["weather_key"].isin(existing_keys)]
    print(f"  To fetch: {len(to_fetch)}")
    print(f"  Estimated time: {len(to_fetch) * 0.15 / 60:.0f}-{len(to_fetch) * 0.3 / 60:.0f} minutes\n")

    t0 = time.time()
    fetched = 0
    errors = 0
    checkpoint_path = OUT_PATH.with_suffix(".checkpoint.csv")

    for i, (_, row) in enumerate(to_fetch.iterrows()):
        lat_r = int(row["lat_r"])
        lon_r = int(row["lon_r"])
        year = int(row["year"])
        month = int(row["month"])
        wkey = row["weather_key"]

        # Find nearest station (cache by rounded loc)
        loc_key = (lat_r, lon_r)
        if loc_key not in station_cache:
            sid, dist = find_nearest_station(lat_r, lon_r, stations)
            station_cache[loc_key] = (sid, dist)
        sid, dist = station_cache[loc_key]

        # Fetch from IEM
        wx = fetch_iem_monthly(sid, year, month)
        time.sleep(0.1)

        if wx:
            record = {
                "weather_key": wkey,
                "lat_r": lat_r,
                "lon_r": lon_r,
                "year": year,
                "month": month,
                "station_id": sid,
                "station_distance_km": round(dist, 1),
            }
            record.update(wx)
            results.append(record)
            fetched += 1
        else:
            results.append(_empty_record(lat_r, lon_r, year, month, wkey))
            errors += 1

        # Progress
        if (i + 1) % 100 == 0 or i == len(to_fetch) - 1:
            elapsed = time.time() - t0
            rate = (i + 1) / elapsed if elapsed > 0 else 0
            eta = (len(to_fetch) - i - 1) / rate if rate > 0 else 0
            pct = (i + 1) / len(to_fetch) * 100
            print(
                f"  [{i+1:>5}/{len(to_fetch)}] {pct:5.1f}% | "
                f"fetched={fetched} errors={errors} | "
                f"{rate:.1f}/s | ETA {eta/60:.0f}m"
            )

        # Checkpoint every 200 keys
        if (i + 1) % 200 == 0:
            _save_checkpoint(results, checkpoint_path)

    # Final save
    out_df = pd.DataFrame(results)
    for c in OUT_COLS:
        if c not in out_df.columns:
            out_df[c] = np.nan
    out_df[OUT_COLS].to_csv(OUT_PATH, index=False)

    elapsed = time.time() - t0
    print(f"\nCompleted in {elapsed:.0f}s ({elapsed/60:.1f} minutes)")
    print(f"Saved {len(out_df)} records to {OUT_PATH}")

    # Coverage stats
    has_data = out_df["n_days_data"].fillna(0).gt(0)
    has_pressure = out_df["wx_pressure_mean"].notna()
    print(f"\n  === COVERAGE ===")
    print(f"  Total keys: {len(out_df)}")
    print(f"  With any data: {has_data.sum()} ({has_data.mean()*100:.1f}%)")
    print(f"  With pressure: {has_pressure.sum()} ({has_pressure.mean()*100:.1f}%)")

    for col in OUT_COLS:
        if col.startswith("wx_"):
            n = out_df[col].notna().sum()
            print(f"    {col}: {n}/{len(out_df)} ({n/len(out_df)*100:.1f}%)")

    # Clean checkpoint
    if checkpoint_path.exists():
        checkpoint_path.unlink()

    print("\nDone!")


if __name__ == "__main__":
    main()
